// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Problema_2._5.Models;

public partial class db_productosContext : DbContext
{
    public db_productosContext(DbContextOptions<db_productosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<PRODUCTO> PRODUCTOs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PRODUCTO>(entity =>
        {
            entity.HasKey(e => e.codigo);

            entity.ToTable("PRODUCTOS");

            entity.Property(e => e.fecha_baja).HasColumnType("datetime");
            entity.Property(e => e.motivo_baja)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}