// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Problema_2._5.Models;

public partial class PRODUCTO
{
    public int codigo { get; set; }

    public string nombre { get; set; }

    public float precio { get; set; }

    public DateTime? fecha_baja { get; set; }

    public string motivo_baja { get; set; }
}